### ISSUE TITLE
maximum recursion depth exceeded for typing.Literal

### ISSUE THREAD

**Issue by cgebbe** [bojiang/typing_utils#10] opened 2022-03-10 14:07 UTC
`issubtype(typing.Literal["max"], typing.Literal)` yields a "maximum recursion depth exceeded". Is this expected?

**Comment by bryant1410** [comment] 2022-04-15 18:51
The root of the problem is that `issubtype` calls `normalize`, which in turn calls `_normalize_args`, checking if the argument is a sequence. A string is a sequence, but also each of its elements as an iterable is a string, so then you enter into infinite recursion with the first character ("m").

I think an extra guard checking for a string-like type needs to be done.

**Comment by apirogov** [comment] 2022-09-16 13:02
I've also run into this. Could the fix be merged? Is someone still maintaining this?

I basically installed this package just for the `issubtype` function.

**Closed as completed** 2022-11-09 04:50 UTC
